from . import hr_payslip_custom
from . import salaries_excel_sheet
from . import employee_loan
from . import employee_checklist_for_staff
from . import employee_checklist_for_staff_employee
from . import employee_induction_form
from . import employee_induction_for_master_data
from . import staff_induction_sheet
from . import payroll
from . import master_data_salary_computation
from . import interview_rating_guide
from . import fastra_leave_request